spring.application.name=demo
server.port=8080
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=n12update;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
# spring.datasource.url=jdbc:sqlserver://DESKTOP-R8J6D5M\\MSSQLSERVER1:1433;encrypt=true;trustServerCertificate=true;databaseName=schoolmanager
# spring.datasource.username=sa
# spring.datasource.password=123123
# spring.datasource.url=jdbc:sqlserver://den1.mssql7.gear.host:1433;encrypt=true;trustServerCertificate=true;databaseName=school123456
# spring.datasource.username=school123456
# spring.datasource.password=Tf1XN700~Y!T
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# ===== Swagger / SpringDoc OpenAPI =====
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.filter=true