spring.application.name=demo

server.port=${PORT:8080}

# PostgreSQL Render
spring.datasource.url=jdbc:postgresql://dpg-d86qspd7vvec73aid0d0-a.virginia-postgres.render.com:5432/data_apz6

spring.datasource.username=data_apz6_user

spring.datasource.password=xwH8cKUa7abd2uQvJy1BqjQBbg9GopfH

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
